services:
  sql_container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_container
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit-server
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - mynetwork

  sale:
    build:
      context: .
      dockerfile: Sale/Dockerfile
    image: sale_image
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_container,1433;Database=SalesDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sql_container
      - rabbitmq
    networks:
      - mynetwork

  stock:
    build:
      context: .
      dockerfile: StockSale/Dockerfile
    image: stock_image
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql_container,1433;Database=StockDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - sql_container
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sql_data:
